/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const AuthenticationLoginLazyImport = createFileRoute('/authentication/login')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationLoginLazyRoute = AuthenticationLoginLazyImport.update({
  path: '/authentication/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/authentication/login.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/authentication/login': {
      id: '/authentication/login'
      path: '/authentication/login'
      fullPath: '/authentication/login'
      preLoaderRoute: typeof AuthenticationLoginLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authentication/login': typeof AuthenticationLoginLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authentication/login': typeof AuthenticationLoginLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/authentication/login': typeof AuthenticationLoginLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/authentication/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/authentication/login'
  id: '__root__' | '/' | '/authentication/login'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticationLoginLazyRoute: typeof AuthenticationLoginLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticationLoginLazyRoute: AuthenticationLoginLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/authentication/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/authentication/login": {
      "filePath": "authentication/login.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
